live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/argonaut.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "on"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Rec Mono Casual"
style = "Bold"

[font.bold_italic]
family = "Rec Mono Casual"
style = "Bold Italic"

[font.italic]
family = "Rec Mono Casual"
style = "Italic"

[font.normal]
family = "Rec Mono Casual"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t@="

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
opacity = 0.93

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 5
